// References links to specific rule violation (https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md)
export default {
  'area-alt': [],
  'aria-allowed-attr': [],
  'aria-hidden-body': [],
  'aria-hidden-focus': [],
  'aria-input-field-name': [],
  'aria-required-attr': [],
  'aria-required-children': [],
  'aria-required-parent': [],
  'aria-roledescription': [],
  'aria-roles': [],
  'aria-toggle-field-name': [],
  'aria-valid-attr-value': [],
  'aria-valid-attr': [],
  'audio-caption': [],
  blink: [],
  'button-name': [],
  bypass: [],
  'color-contrast': [
    {
      title: 'Colors with Good Contrast (w3.org)',
      link: 'https://www.w3.org/WAI/perspective-videos/contrast/'
    },
    {
      title: 'Contrast and Color Accessibility (WebAIM)',
      link: 'https://webaim.org/articles/contrast/'
    },
    {
      title: 'Color and contrast accessibility (web.dev)',
      link: 'https://web.dev/color-and-contrast-accessibility/'
    }
  ],
  'definition-list': [],
  dlitem: [],
  'document-title': [],
  'duplicate-id-active': [],
  'duplicate-id-aria': [],
  'duplicate-id': [],
  'form-field-multiple-labels': [],
  'frame-title': [],
  'html-has-lang': [],
  'html-lang-valid': [],
  'html-xml-lang-mismatch': [],
  'image-alt': [],
  'input-button-name': [],
  'input-image-alt': [],
  label: [],
  'link-name': [],
  list: [],
  listitem: [],
  marquee: [],
  'meta-refresh': [],
  'object-alt': [],
  'role-img-alt': [],
  'scrollable-region-focusable': [],
  'select-name': [],
  'server-side-image-map': [],
  'svg-img-alt': [],
  'td-headers-attr': [],
  'th-has-data-cells': [],
  'valid-lang': [],
  'video-caption': [],
  'autocomplete-valid': [],
  'avoid-inline-spacing': [],
  accesskeys: [],
  'aria-allowed-role': [],
  'empty-heading': [],
  'frame-tested': [],
  'frame-title-unique': [],
  'heading-order': [],
  'identical-links-same-purpose': [],
  'image-redundant-alt': [],
  'label-title-only': [],
  'landmark-banner-is-top-level': [],
  'landmark-complementary-is-top-level': [],
  'landmark-contentinfo-is-top-level': [],
  'landmark-main-is-top-level': [],
  'landmark-no-duplicate-banner': [],
  'landmark-no-duplicate-contentinfo': [],
  'landmark-no-duplicate-main': [],
  'landmark-one-main': [],
  'landmark-unique': [],
  'meta-viewport-large': [],
  'meta-viewport': [],
  'page-has-heading-one': [],
  region: [],
  'scope-attr-valid': [],
  'skip-link': [],
  tabindex: [],
  'table-duplicate-name': [],
  'css-orientation-lock': [],
  'focus-order-semantics': [],
  'hidden-content': [],
  'label-content-name-mismatch': [],
  'link-in-text-block': [],
  'no-autoplay-audio': [],
  'p-as-heading': [],
  'table-fake-caption': [],
  'td-has-header': []
}
